spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/v1/

